# Generated by Django 3.0.7 on 2020-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='text of the review')),
                ('review_prediction', models.IntegerField(verbose_name='prediction of the review')),
            ],
        ),
        migrations.DeleteModel(
            name='Review_Prediction',
        ),
    ]
