# Generated by Django 3.0.7 on 2020-06-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='prediction_proba',
            field=models.CharField(default='(100%)', max_length=10, verbose_name='prediction probability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review_stars',
            field=models.CharField(default='(...)', max_length=30, verbose_name='star prediction'),
            preserve_default=False,
        ),
    ]
