# Generated by Django 3.0.7 on 2020-06-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200625_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_stars',
            field=models.CharField(max_length=50, verbose_name='star prediction'),
        ),
    ]
